### ISSUE TITLE
Logical acquisition fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by ridale** [jfarley248/MEAT#2]
The serial number in ```pymobiledevice2/usbmux/usbmux.py``` is returned as a byte array so string split fails with a stack dump. The following patch fixes it for me but may break other platforms. It is probable that checking the returned type of  ```serial``` and doing the decode if it is a byte array is the correct fix.

```
diff --git a/pymobiledevice2/usbmux/usbmux.py b/pymobiledevice2/usbmux/usbmux.py
index 2b0741f..707c18c 100644
--- a/pymobiledevice2/usbmux/usbmux.py
+++ b/pymobiledevice2/usbmux/usbmux.py
@@ -108,7 +108,7 @@ class BinaryProtocol(object):
             return {'Number': struct.unpack("I", payload)[0]}
         elif resp == self.TYPE_DEVICE_ADD:
             devid, usbpid, serial, pad, location = struct.unpack("IH256sHI", payload)
-            serial = serial.split("\0")[0]
+            serial = serial.decode("utf-8").split("\0")[0]
             return {'DeviceID': devid,
                     'Properties': {'LocationID': location, 'SerialNumber': serial, 'ProductID': usbpid}}
         elif resp == self.TYPE_DEVICE_REMOVE:
```

**Comment by ridale** [comment]
Also most of the file path code would need to be changed as the "\\" seperators cause issues with linux. I have replaced them with os.sep but there are other path issues with the translation of the iphone paths for windows. As the system runs on Python post 3.4 I could replace the path code with pathlib ```https://docs.python.org/3/library/pathlib.html``` and create a pull request if you are interested?

**Comment by jfarley248** [comment]
Hi, thanks for letting me know. I haven't tested with Linux but I'll spin up a VM and implement that fix you provided and make sure it works on both Linux and Windows.

**Comment by jfarley248** [comment]
Just remembered a similar issue I had in another repo of mine. I should be using `os.path.join()` instead of just `+ "//"`, sloppy coding on my part, but that should fix it cross platform.

**Comment by jfarley248** [comment]
Hello @ridale, just pushed a fix to this issue and tested on Linux and Windows. If you could see if these fixes work for you that'd be great.

**Comment by ridale** [comment]
Tested on Ubuntu 18.04 all good now, thanks for that, great project.
